// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CDefault: typeof import('./src/components/ConfigForm/controls/CDefault.vue')['default']
    CGroup: typeof import('./src/components/ConfigForm/controls/CGroup.vue')['default']
    CInput: typeof import('./src/components/ConfigForm/controls/CInput.vue')['default']
    CList: typeof import('./src/components/ConfigForm/controls/CList.vue')['default']
    CMenu: typeof import('./src/components/ConfigForm/controls/CMenu.vue')['default']
    ConfigForm: typeof import('./src/components/ConfigForm/index.vue')['default']
    ControlWrapper: typeof import('./src/components/ConfigForm/core/ControlWrapper.vue')['default']
    CRadio: typeof import('./src/components/ConfigForm/controls/CRadio.vue')['default']
    CSelect: typeof import('./src/components/ConfigForm/controls/CSelect.vue')['default']
    CSlider: typeof import('./src/components/ConfigForm/controls/CSlider.vue')['default']
    CSuite: typeof import('./src/components/ConfigForm/controls/CSuite.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
