// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/ConfigForm/controls/CSuite copy 2.vue')['default']
    CDefault: typeof import('./src/components/ConfigForm/controls/CDefault.vue')['default']
    CGroup: typeof import('./src/components/ConfigForm/controls/CGroup.vue')['default']
    CList: typeof import('./src/components/ConfigForm/controls/CList.vue')['default']
    CMenu: typeof import('./src/components/ConfigForm/controls/CMenu.vue')['default']
    ConfigForm: typeof import('./src/components/ConfigForm/index.vue')['default']
    ControlWrapper: typeof import('./src/components/ConfigForm/core/ControlWrapper.vue')['default']
    copy: typeof import('./src/components/ConfigForm/controls/CSuite copy.vue')['default']
    CSelect: typeof import('./src/components/ConfigForm/controls/CSelect.vue')['default']
    CSuite: typeof import('./src/components/ConfigForm/controls/CSuite.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
